[2021-06-08 14:39:49,899] [ERROR] [app.controllers] [Thread-2] : {'status_code': 400, 'url': 'http://localhost:8089/connectors/', 'method': 'GET', 'message': "error encountered HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /connectors (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f265e489080>: Failed to establish a new connection: [Errno 111] Connection refused',))"}
[2021-06-08 14:40:09,892] [ERROR] [app.controllers] [Thread-3] : {'status_code': 400, 'url': 'http://localhost:8089/connectors/', 'method': 'GET', 'message': "error encountered HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /connectors (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f265dc1e748>: Failed to establish a new connection: [Errno 111] Connection refused',))"}
[2021-06-08 14:40:10,906] [ERROR] [app.controllers] [Thread-4] : {'status_code': 400, 'url': 'http://localhost:8089/connectors/', 'method': 'GET', 'message': "error encountered HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /connectors (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f265dc1e518>: Failed to establish a new connection: [Errno 111] Connection refused',))"}
